contact/urls.py
from django.urls import path
from . import views

app_name = "contact"
urlpatterns = [
    path("", views.ContactView.as_view(), name="contact"),
    path("success", views.SuccessView.as_view(), name="success"),
    path("waitlist", views.WaitListView.as_view(), name="waitlist"),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about", views.AboutView.as_view(), name="about"),
    path("refundpolicy", views.RefundPolicy.as_view(), name="refundpolicy"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="shop"),
    path(
        "library/",
        views.ProductInstanceList.as_view(),
        name="product-instance-list",
    ),
    path("<slug:slug>", views.product_detail_view, name="product-detail"),
    path("download/<slug:slug>/<str:distributable_id>", views.product_download, name="product-download"),
]

soundspruce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("pages.urls")),
    path("contact", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("", include("accounts.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

soundspruce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        {% if title %}
            <title>{{ title }} - SoundSpruce</title>
        {% else %}
            <title>SoundSpruce</title>
        {% endif %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
        <!-- Bootstrap icons-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/custom-styles.css' %}"/>

    </head>
    <body class="d-flex flex-column vh-100">
        <!-- Responsive navbar-->

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'pages:home' %}"><span class="h2">SoundSpruce</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'pages:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pages:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:shop' %}">Shop</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact' %}">Contact</a></li>

                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.get_username }}
                              </a>
                              <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'shop:product-instance-list' %}">My Products</a>
                                <!-- <a class="dropdown-item" href="#">Account details</a> -->
                                <div class="dropdown-divider"></div>
                                <form class="dropdown-item" id="logout-form" method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-secondary">Logout</button>
                                    </form>
                              </div>

                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            {% block content %} {% endblock %}
        </main>

        <!-- Footer"-->
        <footer class="footer mt-auto py-5 bg-dark">

            <div class="container px-4 px-lg-5">
                <a class="nav-link text-white" href="{% url 'pages:refundpolicy' %}">Refund Policy</a>
                <p class="m-0 text-center text-white">Copyright &copy; SoundSpruce 2025</p>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Popper JS -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

        <script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>

    </body>
</html>

soundspruce/templates/header.html
<nav>
    <a href="{% url 'pages:home' %}">Home</a>
    <a href="{% url 'pages:about' %}">About</a>
    <a href="{% url 'shop:shop' %}">Shop</a>
    <a href="{% url 'contact:contact' %}">Contact</a>
    {# <a href="{% url 'pages:articles' %}">Articles</a> #}


    {% if user.is_authenticated %}
        <label for="user">Hello {{ user.get_username }}!</label>
        <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link">Logout</button>
            </form>
        </li>
        <li>
            <a href="{% url 'shop:product-instance-list' %}">My Products</a>
        </li>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
    {% endif %}
</nav>