shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="shop"),
    path(
        "library/",
        views.ProductInstanceList.as_view(),
        name="product-instance-list",
    ),
    path("<slug:slug>", views.product_detail_view, name="product-detail"),
    path("download/<slug:slug>/<str:distributable_id>", views.product_download, name="product-download"),
]

soundspruce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("pages.urls")),
    path("contact", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("", include("accounts.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/pages/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="py-4">
        <div class="container px-4">
            <div class="row gx-4 gx-lg-5">

                <div class="col-md-6">
                    <h1 class="display-5">About</h1>
                    <p>Hello! My name's Sam, I'm a sound engineer and field recordist.</p>
                    <p>SoundSpruce is my way of gaining programming experience by making tools for the community that I love!</p>
                    <p>My goal is to provide neat easy to use tools that excel at a specific task for professionals working within the industry.</p>
                </div>
                <div class="col-md-6">
                    <div class="carousel-item active">
                        <img src="{% static 'assets/blueboy.jpg' %}" class="d-block w-100" alt="A picture of sam wearing a blue t-shirt and blue shorts">
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock content %}

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="./Styles/layout.css">

    {% if title %}
        <title>{{title}} - SoundSpruce</title>
    {% else %}
        <title>SoundSpruce</title>
    {% endif %}
</head>
<body>
    <header>
        {% include "pages/header.html" %}
    </header>

    <main>
        {% block content %} {% endblock %}
    </main>

    <footer>
        {% include "pages/footer.html" %}
    </footer>
</body>
</html>

pages/templates/pages/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- Page Content-->
     <!-- Header-->
     <header class="bg-dark py-5">
        <div class="container px-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center my-5">
                        <h1>
                            <span class="display-5 text-white mb-2">Do one thing</span><br>
                            <span class="display-1 fw-bolder text-white mb-2 background-mask-text">Do it well</span>
                        </h1>
                        <p class="lead text-white-50 mb-4">Solutions to niche problems, solved with efficient and straight forward tools</p>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'shop:shop' %}">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Features section-->
    <section class="py-5 border-bottom" id="features">
        <div class="container d-flex justify-content-center px-5 my-5">
            <div class="row gx-5 justify-content-center">
                <!-- Video column -->
                <div class="col-lg-6 mb-5 mb-lg-0 d-flex align-items-center">
                    <div class="video-container w-100">
                        <video autoplay muted loop class="w-100">
                            <source src="{% static 'assets/SFC1.3.2banner.mp4' %}" type="video/mp4">
                        </video>
                    </div>
                </div>
                <!-- Content column -->
                <div class="col-lg-6 mb-lg-0 d-flex flex-column align-items-center">
                    <h2 class="h2 fw-bolder text-center">SausageFileConverter</h2>
                    <div class="my-5">
                        <div class="my-3">
                            <i class="bi-lightning-fill"></i> Speed up your workflow by streamlining your sound library
                        </div>
                        <div class="my-3">
                            <i class="bi-arrow-repeat"> Hassle free batch conversion </i>
                        </div>
                        <div class="my-3">
                            <i class="bi-file-earmark-richtext"> Retain metadata, including SoundMiner! </i>
                        </div>
                    </div>
                    <a class="text-decoration-none" href="{% url 'shop:product-detail' slug='sausage-file-converter' %}">
                        See details
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Testimonials section-->
    <section class="py-5 border-bottom">
        <div class="container px-5 my-5 px-5">
            <div class="text-center mb-5">
                <h2 class="fw-bolder">Customer testimonials</h2>
                <p class="lead mb-0">Our customers love our products</p>
            </div>

            <h3 class="text-center">Files converted</h3>
            <div class="my-3 container-md spinner-box text-center">
                <span class="spinner-number" data-val="41634">37481</span>
            </div>

            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <!-- Testimonial 1-->
                    <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1">SausageFileConverter is an absolute <b>must-have</b> for managing sound file bloat.  It's saved me <b>countless hours</b> of manual one-shot consolidation and made my library so much <b>quicker to navigate</b>.  Highly recommend!</p>
                                    <div class="small text-muted">- <a href="https://www.andrewvscott.com/">Andrew Scott</a>, Sound Designer, Intrepid Studios</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial 3-->
                    <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1"><b>SausageFileConverter solves a problem we all run into:</b> I have a hundred one shot sound effects and this really should only be a hand full. <b>This program rocks, you really couldn't ask for something simpler</b> to batch your one shots together. Previously I'd have to make my sausage files by hand, or run a sox script to mash my files together. Now I simply pick the directory, and <b>boom</b>, all similar named files are now a string out, spaced with silence between takes, and <b>all metadata in tact!</b></p>
                                    <div class="small text-muted">- <a href="">Kai Paquin</a>, Head SFX Librarian and Recordist, Skywalker Sound</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial 5-->
                     <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1"><b>THE SAUSAGE FILE CONVERTER IS INCREDIBLE</b>. I am SO, so <b>happy</b> with it.  The file formatting options are <b>fantastic</b>, and the log is so helpful in determining particular issues to separate files with different bit depths and such.  <b>It's actually helping me find a ton of inconsistencies</b> I didn't even realize were there to begin with amongst some of the big-name "pro" libraries... Which is so cool and an added bonus!  <b>I'm so glad Sam created this tool!!</b></p>
                                    <div class="small text-muted">- <a href="http://andrewcorbitt.com/">Andrew Corbitt</a>, Senior Sound Designer, Formerly Formosa Interactive and Playstation Studios Sound</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <!-- Testimonial 2-->
                    <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1">SausageFileConverter is such an <b>amazing and practical tool</b> for me. It has <b>saved me hours and hours of tedious work</b> consolidating various libraries into a more convenient sausage file structure. Sam is a great dev, always listening to feedback and implementing them quickly in new releases. I can't wait to check out the evolution of this awesome piece of software. <b>A must have!</b></p>
                                    <div class="small text-muted">- <a href="https://bruits.studio/">Tibo Csuko</a>, Lead Sound Designer, Bruits.Studio</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial 4-->
                     <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1">Every FX editor knows the <b>hassle</b> of dealing with 1 to 2 second files in <b>dozens</b> of variations. We want a large variety on the timeline at once, waiting in the handles to avoid repetition. Sam's program <b>intelligently finds and joins</b> these files, eliminating the need to spot one-shots like door closes or gore splats. It also <b>cuts down your library size</b>. A particular gun foley library I have has every sound as a separate file—searching “pistol trigger” returns 1,200 results. It's <b>overwhelming to audition that many files</b>, and they obscure the rest of your library from being found. Now my pistol triggers are <b>conveniently located in 10-12 sausage files</b>, each labeled by make of gun. <b>This tool is a must-have for any FX editor.</b></p>
                                    <div class="small text-muted">- <a href="https://www.imdb.com/name/nm2990170/">Jon Lipman</a>, Sound Designer, Sony Pictures Entertainment</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Testimonial 6-->
                    <div class="card mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex">
                                <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                <div class="ms-4">
                                    <p class="mb-1">If you have found SausageFileConverter useful, get in contact, I'd love to promote your testimonial!</p>
                                    <div class="small text-muted">- <a href="">Your Name Here</a>, Sound Designer</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

pages/templates/pages/refund_policy.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="py-4">
        <div class="container px-4">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-6">
                    <h1 class="display-5">Refund and Dispute Policy</h1>
                    <p>At SoundSpruce I am committed to quality and customer satisfaction.</p>
                    <p>If an issue arises with the software that makes it unfit for purpose, in the installation or running of the software, I am happy to provide a full refund if it is brought to my attention within 30 days of purchase.</p>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock content %}