contact/urls.py
from django.urls import path
from . import views

app_name = "contact"
urlpatterns = [
    path("", views.ContactView.as_view(), name="contact"),
    path("success", views.SuccessView.as_view(), name="success"),
    path("waitlist", views.WaitListView.as_view(), name="waitlist"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="shop"),
    path(
        "library/",
        views.ProductInstanceList.as_view(),
        name="product-instance-list",
    ),
    path("<slug:slug>", views.product_detail_view, name="product-detail"),
    path("download/<slug:slug>/<str:distributable_id>", views.product_download, name="product-download"),
]

soundspruce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("pages.urls")),
    path("contact", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("", include("accounts.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage

protected_files = FileSystemStorage(location='protected/')

CATEGORY_CHOICES = (("S", "Software"),)


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    stripe_product_id = models.CharField(
        max_length=220, blank=True, null=True, unique=True
    )
    slug = models.SlugField(unique=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product-detail", args=[self.slug])

    def get_product_description(self):
        return self.productcontenttext_set.filter(type="LONG").order_by("order")

    def get_accordion_sections(self):
        return self.productcontenttext_set.filter(type="ACCORDION").order_by("order")

    def get_carousel_images(self):
        return self.productcontentcarousel_set.order_by("order")

    def get_videos(self):
        return self.productcontentvideo_set.order_by("order")

    def get_images(self):
        return self.productcontentimage_set.order_by("order")

    def get_product_distributables(self):
        return self.productdistributable_set.order_by("order")

class ProductContentBlock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=120)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']
        abstract = True

class ProductContentText(ProductContentBlock):
    TEXT_TYPE_CHOICES = [
        ("ACCORDION", "Text content for an accordion element"),
        ("LONG", "Long text description"),
        ("SHORT", "Short text description")
    ]

    type = models.CharField(blank=False, max_length=120, choices=TEXT_TYPE_CHOICES)
    content = models.TextField(blank=False)

class ProductContentVideo(ProductContentBlock):
    video = models.URLField(blank=False)

class ProductContentImage(ProductContentBlock):
    image = models.ImageField(blank=True, upload_to="images/")

class ProductContentCarousel(ProductContentBlock):
    carousel_image = models.ImageField(blank=False, upload_to="images/")
    lightbox_image = models.ImageField(blank=True, upload_to="images/")

# not yet implemented
class ProductDistributable(ProductContentBlock):

    DISTRIBUTABLE_TYPE_CHOICES = [
        ("PC", "PC executable"),
        ("MAC_ARM", "Mac silicon executable"),
        ("MAC_INTEL", " Mac Intel executable"),
    ]

    type = models.CharField(blank=False, choices=DISTRIBUTABLE_TYPE_CHOICES, max_length=120)
    file = models.FileField(storage=protected_files, blank=False)


class Price(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    stripe_price_id = models.CharField(max_length=100, unique=True)
    price = models.IntegerField(default=0)

    def get_display_price(self):
        return f"{self.price / 100:.2f}"


class ProductInstance(models.Model):
    """SN and purchase date are auto-generated, product and purchaser are assigned at creation"""

    serial_number = models.UUIDField(default=uuid.uuid4, primary_key=True)
    purchase_date = models.DateTimeField(auto_now_add=True)

    product = models.ForeignKey("Product", on_delete=models.RESTRICT)
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )
    mac_download_allowed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("product-instance-detail", args=[str(self.serial_number)])

shop/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseBadRequest, HttpResponse
from django.shortcuts import get_object_or_404

# Create your views here.

from django.views import generic

from shop.models import Product, Price, ProductInstance, ProductDistributable


class ProductListView(generic.ListView):
    model = Product
    extra_context = {"title": "Shop"}


def product_detail_view(request, slug):
    """product detail view, is owner is passed to see if purchase button should be shown or not."""
    product = get_object_or_404(Product, slug=slug)
    price = get_object_or_404(Price, product=product)
    is_owner = False
    if request.user.is_authenticated:
        is_owner = (
            request.user.purchase_set.all()
            .filter(product=product, completed=True)
            .exists()
        )
    context = {"product": product, "price": price, "is_owner": is_owner}
    return render(request, "shop/product_detail.html", context)


class ProductInstanceList(LoginRequiredMixin, generic.ListView):
    model = ProductInstance
    context_object_name = "purchased_products_list"

    def get_queryset(self) -> QuerySet[Any]:
        return ProductInstance.objects.filter(purchaser=self.request.user)


@login_required()
def product_download(request, slug, distributable_id):

    product = get_object_or_404(Product, slug=slug)
    download_allowed = (
        request.user.productinstance_set.all().filter(product=product).exists()
    )

    distributable_instance = get_object_or_404(ProductDistributable, id=distributable_id, product=product)

    if not download_allowed:
        return HttpResponseBadRequest(
            "Bad Request, This product is not on your purchased list."
        )

    #NGINX setup
    response = HttpResponse()
    response['Content-Disposition'] = f'attachment; filename="{distributable_instance.file.name}'
    response['X-Accel-Redirect'] = f'/protected/{distributable_instance.file.name}'

    return response

shop/templates/shop/product_detail.html
{% extends "base.html" %}
{% load custom_tags %}
{% block content %}

{% with carousel_images=product.get_carousel_images %}
<section class="py-5">
    <div class="container px-4">
        <div class="row gx-4 gx-lg-5 align-items-center">
            {% if carousel_images %}
            <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide shadow-drop-2-center img-thumbnail">
                    <div class="carousel-indicators">
                        {% for image in carousel_images %}
                        <button type="button"
                            data-bs-target="#carouselExampleIndicators"
                            data-bs-slide-to="{{ forloop.counter0 }}"
                            class="{% if forloop.first %}active{% endif %}"
                            aria-current="{% if forloop.first %}true{% endif %}"
                            aria-label="Slide {{forloop.counter}}">
                        </button>
                        {% endfor %}
                    </div>
                    <div class="carousel-inner">
                        {% for image in carousel_images %}
                            {% if image.carousel_image %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <a href="/media/{% if image.lightbox_image %}{{ image.lightbox_image }}{% else %}{{ image.carousel_image }}{% endif %}" data-toggle="lightbox" class="d-block w-100 img-fluid" data-caption="{{ image.title }}">
                                    <img src="/media/{{ image.carousel_image }}" class="img-fluid" alt="{{ image.title }}">
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            {% else %}
                missing carousel_images
            {% endif %}
{% endwith %}
            <div class="col-md-6">
                <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                <div class="fs-5 mb-5">
                    <span><s style="color:red;">£75</s> £{{ price.get_display_price }} - Early bird pricing until July 7th.</span>
                </div>
                <p class="lead">{{ product.get_product_description.first.content|linebreaksbr }}</p>
                <div class="d-flex">
                    {% if is_owner %}
                        <p>You own this product.</p>
                    {% else %}
                    <div>
                        {% include 'purchase/buy-btn-form.html' with product=product is_auth=is_auth %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</section>

<section>
{% with accordion_sections=product.get_accordion_sections %}
    {% if accordion_sections %}
        <div class="container px-4 accordion" id="productFeatureAccordion">
            {% for section in accordion_sections %}
                {% with heading_id="heading-"|concat_prefix_to_id:section.id %}
                {% with accordion_id="collapse-"|concat_prefix_to_id:section.id %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="{{ heading_id }}">
                        <button class="accordion-button {% if not forloop.first %}collapsed{% endif %}"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#{{ accordion_id }}"
                                aria-expanded="{% if forloop.first %}true{% else %}false{% endif %}"
                                aria-controls="{{ accordion_id }}">
                        {{ section.title }}
                        </button>
                    </h2>
                    <div id="{{ accordion_id }}"
                        class="accordion-collapse collapse {% if forloop.first %}show{% endif %}"
                        aria-labelledby="{{ heading_id }}"
                        data-bs-parent="#productFeatureAccordion">
                        <div class="accordion-body">
                            {{ section.content|safe }}
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endwith %}
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}
</section>

<section class="py-5">
{% with product_videos=product.get_videos %}
    {% if product_videos %}
        {% for video in product_videos %}
        <div class="container px-4">
                <div class="ratio ratio-16x9 col-md-6">
                    <iframe src="{{ video.video }}" title="{{ video.title }}" frameborder="0" allow="clipboard-write; encrypted-media; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
</section>

{% endblock content %}

shop/templates/shop/product_details.html
{% extends "base.html" %}

{% block content %}
<h1> {{ product.name }} </h1>
<div> {{ product.price }}</div>
<h2>About:</h2>
<p> {{ product.description }}</p>
{% endblock content %}

shop/templates/shop/product_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container-lg py-4">
  <h1 class="display-5">Products</h1>
  {% if product_list %}


      {% for product in product_list %}
      <div class="card mt-2 align-items-center py-4" >
        <img src="/media/{{ product.get_images.first.image }}" class="card-img-top shadow-drop-2-center" alt="Product Image">
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">{{product.get_product_description.first.content}}</p>
          <div class="d-grid gap-2 col-4 mx-auto">
            <a href="{{ product.get_absolute_url }}" class="btn btn-primary btn-lg">See Details</a>
          </div>
        </div>
      </div>

      {% endfor %}

  {% else %}
    <p>There are no products.</p>
  {% endif %}
</div>
{% endblock %}

shop/templates/shop/productinstance_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.product.name }}</h1>
<li>Serial number: {{ object.serial_number }}</li>
<li>Purchase Date: {{ object.purchase_date}}</li>

{% endblock %}

shop/templates/shop/productinstance_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-lg py-4">
    <h1 class="display-5">My Products</h1>

    {% if purchased_products_list %}
    <div class="container">
    {% for productinst in purchased_products_list %}
        {% with distributables=productinst.product.get_product_distributables %}
            <div class="card my-5 col-sm-4 text-center">
                <div class="card-header">
                    <a href="{% url 'shop:product-detail' productinst.product.slug %}">{{ productinst.product.name }}</a>
                    <p>Purchase Date: {{ productinst.purchase_date|date:"SHORT_DATE_FORMAT"}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    {% for distributable in distributables %}
                        {% if distributable %}
                            {% if 'MAC' not in distributable.type or 'MAC' in distributable.type and productinst.mac_download_allowed %}
                                <li class="list-group-item d-flex justify-content-around">{{ distributable.title }}
                                    <form action="{% url 'shop:product-download' productinst.product.slug distributable.id %}">
                                        <input type="submit" value="Download"/>
                                    </form>
                                </li>
                            {% else %}
                                <li class="list-group-item">
                                    To download Mac versions, please contact me for a licence agreement.
                                </li>
                            {% endif %}
                        {% else %}
                            <p>No distributable for this product has been added yet.</p>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endwith %}
    {% endfor %}
    <!-- antivirus false positive warning -->

      <div class="alert alert-primary d-flex-column align-items-center" role="alert">
        <div class="card-body" id="exclusiveCollapse">
            <h5 class="card-title">Please note:</h5>
            <p class="card-text">Currently this is an unsigned binary.  If you encounter any issues select your operating system from the list below for troubleshooting information.
                <p>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWindows" aria-expanded="false" aria-controls="collapseExample">
                      Windows
                    </button>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMac" aria-expanded="false" aria-controls="collapseExample">
                        MacOs
                    </button>
                </p>
                <div class="collapse" id="collapseWindows" data-bs-parent="#exclusiveCollapse">
                    <div class="card card-body">
                        <p>Windows Defender SmartScreen blocks unsigned applications until they have gained enough reputation. To bypass it:</p>
                        Click "More info"
                        <img src="{% static 'assets/WindowsSmartScreen.jpg' %}" height="499" width="533">
                        Click "Run Anyway"
                        <img src="{% static 'assets/WindowsSmartScreen2.jpg' %}" height="499" width="533">
                    </div>
                </div>
                <div class="collapse" id="collapseMac" data-bs-parent="#exclusiveCollapse">
                    <div class="card card-body">
                        <p>MacOS Sequoia in particular is extra sensitive to unsigned applications, in order to open it:</p>
                        <ol>
                            <li>On your Mac, choose Apple menu  > System Settings, then click Privacy & Security in the sidebar. (You may need to scroll down.)</li>
                            <li>Go to Security, then click Open.</li>
                            <li>Click Open Anyway.</li>
                            <li>This button is available for about an hour after you try to open the app.</li>
                            <li>Enter your login password, then click OK.</li>
                        </ol>
                        The app is saved as an exception to your security settings and you can open it in the future by double-clicking it, just as you can any authorised app.
                    </div>
                </div>

                <p>If your anti-virus throws a false positive please get in contact with the details of your anti-virus so that I can contact them to have SausageFileConverter added to their whitelist.</p><p>If you experience any other issues please don't hesitate to get in contact with me.</p></p>
        </div>
        <div class="text-center">
            <a href="{% url 'contact:contact' %}" class="btn btn-primary">Contact</a>
        </div>
      </div>
    </div>

    {% else %}
      <p>You own no products... YET!</p>
    {% endif %}
</div>
{% endblock %}