contact/urls.py
from django.urls import path
from . import views

app_name = "contact"
urlpatterns = [
    path("", views.ContactView.as_view(), name="contact"),
    path("success", views.SuccessView.as_view(), name="success"),
    path("waitlist", views.WaitListView.as_view(), name="waitlist"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="shop"),
    path(
        "library/",
        views.ProductInstanceList.as_view(),
        name="product-instance-list",
    ),
    path("<slug:slug>", views.product_detail_view, name="product-detail"),
    path("download/<slug:slug>/<str:distributable_id>", views.product_download, name="product-download"),
]

soundspruce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin", admin.site.urls),
    path("", include("pages.urls")),
    path("contact", include("contact.urls")),
    path("shop/", include("shop.urls")),
    path("", include("accounts.urls")),
    path("purchase/", include("purchase.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.core.validators import EmailValidator

# Create your models here.

PRODUCT_CHOICES = (("P", "PhotoGPStoMetaData"),)


class Enquiry(models.Model):
    first_name = models.CharField(name="first_name", max_length=100, blank=False)
    last_name = models.CharField(name="last_name", max_length=100, blank=False)
    email = models.EmailField(name="email", blank=False, validators=[EmailValidator])
    subject = models.CharField(name="subject", blank=True, max_length=200)
    message = models.TextField(name="message", blank=False)
    sent_date = models.DateTimeField(name="sent_date", auto_now_add=True)


class WaitList(models.Model):
    first_name = models.CharField(name="first_name", max_length=100, blank=False)
    last_name = models.CharField(name="last_name", max_length=100, blank=False)
    email = models.EmailField(name="email", blank=False, validators=[EmailValidator])
    product = models.CharField(choices=PRODUCT_CHOICES, default="P", max_length=20)
    contact_permission = models.BooleanField(
        "Contact me with development updates", default=False
    )
    date = models.DateTimeField(name="date", auto_now_add=True)

contact/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField, ReCaptchaV3

from contact.models import Enquiry, WaitList


class ContactForm(forms.ModelForm):

    captcha = ReCaptchaField(
    widget=ReCaptchaV3(
        attrs={
            'required_score':0.85
        },action="contact"
    )
)
    class Meta:
        model = Enquiry
        fields = ["first_name", "last_name", "email", "subject", "message"]
        widgets = {"message": forms.widgets.Textarea}


class WaitListForm(forms.ModelForm):

    class Meta:
        model = WaitList
        fields = "__all__"
        # fields = ["first_name", "last_name", "email", "product"]

contact/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import FormView, TemplateView, CreateView
from django.urls import reverse_lazy
from django.core.mail import send_mail

# Create your views here.
from soundspruce.settings import DEFAULT_FROM_EMAIL, NOTIFY_EMAIL
from contact.forms import ContactForm, WaitListForm
from contact.models import Enquiry, WaitList


class ContactView(FormView):
    template_name = "contact/contact.html"
    form_class = ContactForm
    extra_context = {"title": "Contact"}

    def form_valid(self, form) -> HttpResponse:
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        email = form.cleaned_data.get("email")
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")

        form.save()

        full_message = f"""
            Received message below from {first_name} {last_name}: {email},
            subject: {subject}
            ________________________
            {message}
            """

        send_mail(
            subject="Received contact form submission",
            message=full_message,
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=[NOTIFY_EMAIL],
        )

        return super(ContactView, self).form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy("contact:success")


class WaitListView(CreateView):
    form_class = WaitListForm
    template_name = "contact/waitlist.html"

    def get_success_url(self) -> str:
        return reverse_lazy("contact:success")


class SuccessView(TemplateView):
    template_name = "contact/success.html"
    extra_context = {"title": "Contact - Success"}

contact/templates/contact/contact.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-lg py-4">
    <h1 class="display-5">Contact</h1>
    <form action="{% url 'contact:contact' %}" method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>

    </form>

</div>
{% endblock content %}

contact/templates/contact/success.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1 class="display-5">Success!</h1>
    <p>Thank you, your message has been sent!</p>
</div>
{% endblock content %}

contact/templates/contact/waitlist.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container-lg py-4">
    <h1 class="display-5">Wait list</h1>
    <p>If you are interested in an upcoming product please show your interest by filling in the form below! This helps me to prioritise what projects to work on and who would like early access!</p>
    <form action="{% url 'contact:waitlist' %}" method="post">

        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Submit</button>

    </form>

</div>
{% endblock content %}